# Generated by Django 4.2.7 on 2024-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
