# Generated by Django 4.2.7 on 2024-05-11 16:11

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_email_alter_customuser_adress_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.manager.UserManager()),
            ],
        ),
    ]
