# Generated by Django 4.2.7 on 2024-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_requires_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер'),
        ),
    ]
