# Generated by Django 4.2.7 on 2023-11-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
