# Generated by Django 4.2.7 on 2024-05-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_product_color_delete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizeqty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_qty', to='myapp.product'),
        ),
    ]
