# Generated by Django 4.2.7 on 2024-05-12 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_product_count_alter_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizeqty',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
    ]
