# Generated by Django 4.2.7 on 2024-03-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_size_slug'),
        ('cart', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.size', verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
